<script setup lang="ts">
import { useEditorStore } from '@/store/editor'

import InlineIconLanguage from '@/assets/icons-inline/language.svg?raw'
import InlineIconSheet from '@/assets/icons-inline/sheet.svg?raw'
import InlineIconNicat from '@/assets/icons-inline/nicat.svg?raw'
import { computed } from 'vue'

import '@/styles/render.sass'

const editor = useEditorStore()

const props = defineProps<{
  renderIndex?: boolean
}>()

const renderIndex = computed(() => {
  return props.renderIndex ?? true
})
</script>

<template>
  <div class="r__render-area">
    <div class="r__sheet-title">
      <div class="r__sheet-icon" role="img" v-html="InlineIconSheet"></div>
      <div class="r__sheet-name">{{ editor.name }}</div>
    </div>

    <div :class="{ 'r__sheet': true, 'r__sheet-with-index': renderIndex }">
      <div v-if="renderIndex" class="r__lang-icon">
        <div class="r__lang-icon__img" role="img" v-html="InlineIconLanguage"></div>
      </div>
      <div class="r__sheet-table">
        <div v-for="id of editor.langs.order" :key="id" class="r__lang">
          {{ editor.langs.dict[id] }}
        </div>
      </div>

      <template v-for="(block, i) of editor.content" :key="i">
        <div v-if="renderIndex" class="r__sheet-index">#{{ i + 1 }}</div>

        <div
          v-if="block.type == 'text'"
          class="r-text">
          <div
            v-for="id of editor.langs.order"
            :key="id"
            class="r-text__item">
            {{ block.content[id] }}
          </div>
        </div>
      </template>
    </div>

    <div class="r__footer">
      <div class="r__sign">
        <div class="r__sign-text">
          <div>Generated by</div>
          <div class="r__sign-site">https://nicat.idl.ist</div>
        </div>
        <div class="r__sign-logo" role="img" v-html="InlineIconNicat"></div>
      </div>
    </div>
  </div>
</template>